# Generated by Django 5.2.17 on 2026-08-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertType',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('signal_terms', models.JSONField(blank=True, default=list, help_text='Terms that signal this role in a tender. Search aid only — never an input to a compliance verdict.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for a top-level family.', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='experts.experttype')),
            ],
            options={
                'verbose_name': 'expert type',
                'verbose_name_plural': 'expert types',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.ManyToManyField(blank=True, limit_choices_to={'parent__isnull': False}, related_name='experts', to='experts.experttype')),
            ],
            options={
                'verbose_name': 'expert',
                'verbose_name_plural': 'experts',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='experttype',
            index=models.Index(fields=['parent', 'position'], name='experts_exp_parent__e78a54_idx'),
        ),
        migrations.AddConstraint(
            model_name='expert',
            constraint=models.UniqueConstraint(condition=models.Q(('linkedin_url', ''), _negated=True), fields=('linkedin_url',), name='expert_unique_linkedin_url'),
        ),
    ]
