# Generated by Django 5.2.16 on 2026-08-10 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0021_alter_contractaward_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedSource',
            fields=[
                ('source_key', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('notice', 'Notice body'), ('document', 'Mirrored document')], db_index=True, max_length=16)),
                ('document_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('indexed', 'Embedded and upserted'), ('empty', 'No chunks worth indexing'), ('failed', 'Embedding or upsert failed')], db_index=True, default='indexed', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('embed_model', models.CharField(blank=True, max_length=64)),
                ('pipeline_version', models.PositiveSmallIntegerField(default=1)),
                ('indexed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexed_sources', to='tenders.tendernotice')),
            ],
            options={
                'verbose_name': 'indexed source',
                'verbose_name_plural': 'indexed sources',
                'ordering': ['-indexed_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='ragidx_kind_status_idx'), models.Index(fields=['-indexed_at'], name='ragidx_indexed_at_idx')],
            },
        ),
    ]
