# Generated by Django 5.2.16 on 2026-08-12 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_indexer', '0002_chatconversation_chatmessage_and_more'),
        ('tenders', '0021_alter_contractaward_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_notice_id', models.CharField(db_index=True, max_length=64)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('match_passage', models.TextField(blank=True)),
                ('algo_version', models.PositiveSmallIntegerField(default=1)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notice', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, related_name='similar_awards', to='tenders.tendernotice')),
            ],
            options={
                'verbose_name': 'similar award',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['notice', 'rank'], name='ragsim_notice_rank_idx')],
                'constraints': [models.UniqueConstraint(fields=('notice', 'award_notice_id'), name='ragsim_unique_pair')],
            },
        ),
    ]
