# Generated by Django 5.2.16 on 2026-07-29 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some pages failed)'), ('failed', 'Failed')], default='running', max_length=16)),
                ('trigger', models.CharField(default='celery-beat', help_text='What started this run: celery-beat, manual, startup…', max_length=32)),
                ('pages_requested', models.PositiveIntegerField(default=0)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('notices_seen', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('upstream_total', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderNotice',
            fields=[
                ('notice_id', models.CharField(help_text='Upstream World Bank notice identifier.', max_length=64, primary_key=True, serialize=False, verbose_name='notice id')),
                ('notice_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notice_status', models.CharField(blank=True, max_length=64)),
                ('notice_language', models.CharField(blank=True, max_length=64)),
                ('notice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline_time', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('project_name', models.TextField(blank=True)),
                ('bid_reference_no', models.CharField(blank=True, max_length=255)),
                ('bid_description', models.TextField(blank=True)),
                ('procurement_group', models.CharField(blank=True, max_length=32)),
                ('procurement_method_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('procurement_method_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_organization', models.CharField(blank=True, max_length=512)),
                ('contact_email', models.CharField(blank=True, max_length=320)),
                ('contact_phone_no', models.CharField(blank=True, max_length=128)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_country', models.CharField(blank=True, max_length=255)),
                ('contact_web_url', models.CharField(blank=True, max_length=512)),
                ('notice_text_sanitized', models.TextField(blank=True)),
                ('notice_text_raw', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of the upstream payload; used to skip no-op writes.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'tender notice',
                'verbose_name_plural': 'tender notices',
                'ordering': ['-notice_date', '-created_at'],
                'indexes': [models.Index(fields=['-notice_date'], name='tender_notice_date_desc_idx'), models.Index(fields=['deadline_date'], name='tender_deadline_idx'), models.Index(fields=['country', '-notice_date'], name='tender_country_date_idx'), models.Index(fields=['procurement_method_code', '-notice_date'], name='tender_method_date_idx'), models.Index(fields=['notice_type'], name='tender_notice_type_idx')],
            },
        ),
    ]
