# Generated by Django 5.2.16 on 2026-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier, e.g. 'recent' or 'country:India'.", max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('recent', 'Recent (unfiltered)'), ('country', 'By country'), ('country_method', 'By country + procurement method')], default='country', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Upstream query parameters that define this partition.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('subdivided', 'Subdivided'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('next_offset', models.PositiveIntegerField(default=0)),
                ('upstream_total', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_done', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'backfill partition',
                'verbose_name_plural': 'backfill partitions',
                'ordering': ['kind', 'key'],
                'indexes': [models.Index(fields=['status', 'kind'], name='backfill_status_kind_idx')],
            },
        ),
    ]
