# Generated by Django 5.2.16 on 2026-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_backfillpartition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tendernotice',
            options={'ordering': [models.OrderBy(models.F('notice_date'), descending=True, nulls_last=True), '-notice_id'], 'verbose_name': 'tender notice', 'verbose_name_plural': 'tender notices'},
        ),
    ]
