# Generated by Django 5.2.16 on 2026-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_postgres_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='team_lead',
            field=models.TextField(blank=True),
        ),
    ]
