# Generated by Django 5.2.16 on 2026-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_projectprofile_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernotice',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering, design & supervision'), ('audit', 'Audit & financial management'), ('environment_social', 'Environmental & social'), ('training', 'Training & capacity building'), ('research', 'Studies, research & evaluation'), ('it_advisory', 'IT & digital advisory'), ('legal_procurement', 'Legal & procurement advisory'), ('management', 'Project management support'), ('other', 'Other consulting'), ('', 'Not sub-classified')], db_index=True, default='', help_text='Sub-direction within Consulting.', max_length=24),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='subcategory_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tendernotice',
            index=models.Index(fields=['subcategory', '-notice_date'], name='tender_subcat_idx'),
        ),
    ]
