# Generated by Django 5.2.16 on 2026-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_tendernotice_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeadProfile',
            fields=[
                ('slug', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, help_text='Global Practice or department, as published.', max_length=255)),
                ('country_office', models.CharField(blank=True, max_length=255)),
                ('work_email', models.CharField(blank=True, max_length=320)),
                ('email_source', models.CharField(blank=True, choices=[('pattern', 'Derived from the staff address pattern'), ('verified', 'Found published on a Bank page')], max_length=16)),
                ('email_confidence', models.FloatField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('links', models.JSONField(blank=True, default=list, help_text='Public URLs found for this person: [{url, kind, label}].')),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'team lead profile',
                'verbose_name_plural': 'team lead profiles',
                'ordering': ['name'],
            },
        ),
    ]
