# Generated by Django 5.2.16 on 2026-08-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_teamleadprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleadprofile',
            name='bank_page_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleadprofile',
            name='bank_page_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teamleadprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography as published on the World Bank author page.'),
        ),
        migrations.AddField(
            model_name='teamleadprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
