# Generated by Django 5.2.16 on 2026-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_notice_project_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedDocument',
            fields=[
                ('url_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('kind', models.CharField(choices=[('tor', 'Terms of Reference'), ('bidding', 'Bidding / tender document'), ('project_doc', 'Project document'), ('other', 'Other linked document')], db_index=True, default='other', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Not fetched yet'), ('fetched', 'Fetched and parsed'), ('access_denied', 'Reachable, but not public'), ('unreachable', 'Could not be fetched'), ('no_text', 'Stored, but no text layer'), ('skipped', 'Rejected before fetching')], db_index=True, default='pending', max_length=16)),
                ('link_context', models.TextField(blank=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stored_path', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField(blank=True)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('has_text_layer', models.BooleanField(blank=True, null=True)),
                ('parser', models.CharField(blank=True, max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notices', models.ManyToManyField(blank=True, related_name='harvested_documents', to='tenders.tendernotice')),
            ],
            options={
                'verbose_name': 'harvested document',
                'verbose_name_plural': 'harvested documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='harvestdoc_status_kind_idx'), models.Index(fields=['-created_at'], name='harvestdoc_created_idx')],
            },
        ),
    ]
