# Generated by Django 5.2.17 on 2026-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_notice_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaward',
            name='awarded_bidders',
            field=models.JSONField(blank=True, default=list, help_text='Every firm named as an awardee — one entry unless it is a joint venture.'),
        ),
        migrations.AddField(
            model_name='contractaward',
            name='rejected_bidders',
            field=models.JSONField(blank=True, default=list, help_text='Bidders rejected before evaluation, with the reason where published.'),
        ),
        migrations.AlterField(
            model_name='contractaward',
            name='evaluated_bidders',
            field=models.JSONField(blank=True, default=list, help_text='Bidders evaluated against the winner and not selected.'),
        ),
    ]
