# Generated by Django 5.2.17 on 2026-08-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_contractaward_awarded_bidders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernotice',
            name='consulting_audience',
            field=models.CharField(blank=True, choices=[('firm', 'Consulting firms'), ('individual', 'Individual consultants'), ('', 'Not determined')], db_index=True, default='', help_text='Whether a consulting notice addresses firms or individuals.', max_length=16),
        ),
    ]
