# Generated by Django 5.2.16 on 2026-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0020_alter_tendernotice_category_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractaward',
            name='currency',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
