# Generated by Django 5.2.17 on 2026-08-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0013_harvesteddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('scalars', models.JSONField(blank=True, default=dict)),
                ('collections', models.JSONField(blank=True, default=dict)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Completed'), ('failed', 'Failed')], default='ok', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='tenders.tendernotice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('L0', 'Implied by the procurement method'), ('L1', 'Deterministic rule over the notice body'), ('L2', 'LLM extraction from the notice body'), ('L3', 'Parsed from a linked document')], db_index=True, max_length=2)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('expression', models.JSONField()),
                ('applies_to', models.CharField(default='single', max_length=16)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('evidence_quote', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('grounding', models.CharField(choices=[('verified', 'Quote found in source'), ('not_found', 'Quote not found — do not use'), ('exempt', 'Standard requirement, cites a regulation'), ('unchecked', 'Not verified yet')], default='unchecked', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tenders.tendernotice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.extractionrun')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='tenders.harvesteddocument')),
            ],
            options={
                'ordering': ['notice_id', 'layer', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['notice', '-created_at'], name='compliance__notice__87d9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['layers', 'model'], name='compliance__layers_0b4a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderrequirement',
            index=models.Index(fields=['notice', 'layer'], name='compliance__notice__9c1e08_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderrequirement',
            index=models.Index(fields=['grounding'], name='compliance__groundi_27a8c2_idx'),
        ),
    ]
