# Generated by Django 5.2.17 on 2026-08-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_vendorprofile_user'),
        ('experts', '0001_initial'),
        ('tenders', '0016_notice_deadline_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderExpertPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('L1', 'Deterministic rule over the notice body'), ('L2', 'LLM extraction from the notice body'), ('L3', 'Parsed from a tender document')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('evidence_quote', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('grounding', models.CharField(choices=[('verified', 'Quote found in source'), ('not_found', 'Quote not found — do not use'), ('unchecked', 'Not verified yet')], default='unchecked', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_positions', to='tenders.tendernotice')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_positions', to='experts.experttype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_positions', to='compliance.extractionrun')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_positions', to='tenders.harvesteddocument')),
            ],
            options={
                'verbose_name': 'tender expert position',
                'verbose_name_plural': 'tender expert positions',
                'ordering': ['notice_id', 'title'],
                'indexes': [models.Index(fields=['notice', 'layer'], name='compliance__notice__c0a237_idx'), models.Index(fields=['role'], name='compliance__role_id_a043ce_idx')],
            },
        ),
    ]
