# Generated by Django 5.2.17 on 2026-08-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_tenderexpertposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='compliance.vendorprofile')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='compliance.tenderrequirement')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['profile', 'requirement'], name='compliance__profile_16f653_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'requirement'), name='one_declaration_per_requirement')],
            },
        ),
    ]
