# Generated by Django 5.2.16 on 2026-08-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_requirementdeclaration'),
        ('tenders', '0016_notice_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequirement',
            name='importance',
            field=models.CharField(blank=True, choices=[('high', 'Decides eligibility'), ('medium', 'Required, not marked either way'), ('low', 'Stated as a preference or an advantage'), ('', 'Not judged')], db_index=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='label_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='label_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('ceiling', models.FloatField(default=0.0)),
                ('earned', models.PositiveIntegerField(default=0)),
                ('open_weight', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('requirements', models.PositiveIntegerField(default=0)),
                ('satisfied', models.PositiveIntegerField(default=0)),
                ('blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_scores', to='tenders.tendernotice')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='compliance.vendorprofile')),
            ],
            options={
                'ordering': ['-score', 'notice_id'],
                'indexes': [models.Index(fields=['profile', '-score'], name='compliance__profile_27137c_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'notice'), name='one_score_per_profile_notice')],
            },
        ),
    ]
