# Generated by Django 5.2.16 on 2026-08-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_tenderrequirement_importance_and_more'),
        ('tenders', '0016_notice_deadline_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_id', models.CharField(max_length=32)),
                ('page', models.PositiveSmallIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('x0', models.FloatField()),
                ('top', models.FloatField()),
                ('x1', models.FloatField()),
                ('bottom', models.FloatField()),
                ('page_width', models.FloatField()),
                ('page_height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='tenders.harvesteddocument')),
            ],
            options={
                'verbose_name': 'compliance span',
                'verbose_name_plural': 'compliance spans',
                'ordering': ['document_id', 'order'],
                'indexes': [models.Index(fields=['document', 'order'], name='compliance__documen_f9c6e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'span_id'), name='one_span_per_document_id')],
            },
        ),
    ]
